material.lib.Balsa_Wood_3x3 = MATERIAL.new( "Balsa_Wood_3x3", "Rectangular", "Standard", {
	Izz = "6.75", 
	Iyy = "6.75", 
	E = "3500", 
	fail = "15", 
	G = "166", 
	width = "3", 
	density = "163", 
	polar = "13.5", 
	f_torsion = "1", 
	f_shear_y = "1", 
	height = "3", 
	fail_type = "Fragile", 
	f_shear_z = "1", 
	area = "9", 
} )