--Materials
mat_file = loadfile("Material Library\\Aluminium_3_diam.lua")
mat_file()
mat_file = loadfile("Material Library\\Aluminium_4_diam.lua")
mat_file()
mat_file = loadfile("Material Library\\Aluminium_5_diam.lua")
mat_file()
mat_file = loadfile("Material Library\\Balsa_Wood_3x3.lua")
mat_file()
mat_file = loadfile("Material Library\\Birch_Wood_10x3.lua")
mat_file()
mat_file = loadfile("Material Library\\Birch_Wood_10x6.lua")
mat_file()
mat_file = loadfile("Material Library\\Birch_Wood_10x9.lua")
mat_file()
mat_file = loadfile("Material Library\\Birch_Wood_15x3.lua")
mat_file()
mat_file = loadfile("Material Library\\Birch_Wood_15x6.lua")
mat_file()
mat_file = loadfile("Material Library\\Birch_Wood_15x9.lua")
mat_file()
mat_file = loadfile("Material Library\\Birch_Wood_16x3.lua")
mat_file()
mat_file = loadfile("Material Library\\Birch_Wood_20x3.lua")
mat_file()
mat_file = loadfile("Material Library\\Carbon_Fiber_Tube_6x4.lua")
mat_file()
mat_file = loadfile("Material Library\\Carbon_Fiber_Tube_6x6.lua")
mat_file()
mat_file = loadfile("Material Library\\Carbon_Fiber_Tube_8x6.lua")
mat_file()
mat_file = loadfile("Material Library\\Steel_10x10.lua")
mat_file()
