--Materials
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Tubo_carbono_6x6_daniel.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Vara_carbono_11X1_8.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Tubo_carbono_6X4.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Vara_carbono_11X1_8_COMP.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\micro.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Al_3_diam.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Birch_10X3.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Aro_roda_AL_2.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Birch_16X3.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Birch_10X6.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Aco_10x10.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Balsa_1_3x3.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Al_5_diam.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Al_4_diam.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Birch_20X3.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Birch_10X9.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Birch_15X9.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Birch_15X6.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Birch_15X3.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Aro_roda_AL.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Tubo_de_cauda_carbono.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Balsa_Lorenzo_Sandwich.lua")
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Tubo_carbono_8X6.lua" )
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Tubo_carbono_6x6.lua" )
mat_file()
mat_file = loadfile( "D:\\Albatroz Parametric v2.0\\Material library\\Tubo_carbono_10x85.lua" )
mat_file()
